groups:

	-name: robot
	joints:
		torso_to
		right_torso_itb_fixed
		right_torso_itb_fixed
		pedestal_fixed
		head_pan
		sonar_s0		
	links:
		base
		left_torso_itb
		right_torso_itb
		pedestal
		head
		torso
		sonar_ring

	-name: robot_head
	joints:
		head_pan
		head_nod
		head_camera
	links:
		screen
		head
		head_camera

	-name: left_arm
	joints:
		left_torso_arm_mount
		left_s0
		left_s1
		left_e0
		left_e1
		left_w0
		left_w0_to_itb_fixed
		left_w1
		left_w2
		left_hand
		left_hand_camera
		left_hand_camera_axis
		left_hand_range
		left_gripper_base
		left_endpoint
	links:
		left_arm_mount
		left_upper_shoulder
		left_lower_shoulder
		left_upper_elbow
		left_lower_elbow
		left_upper_forearm
		left_arm_itb
		left_lower_forearm
		left_wrist
		left_hand
		left_hand_camera
		left_hand_camera_axis
		left_hand_range
		left_gripper_base
		left_gripper

	-name: right_arm
	joints:
		right_torso_arm_mount
		right_s0
		right_s1
		right_e0
		right_e1
		right_w0
		right_w0_to_itb_fixed
		right_w1
		right_w2
		right_hand
		right_hand_camera
		right_hand_camera_axis
		right_hand_range
		right_gripper_base
		right_endpoint
	links:
		right_arm_mount
		right_upper_shoulder
		right_lower_shoulder
		right_upper_elbow
		right_lower_elbow
		right_upper_forearm
		right_arm_itb
		right_lower_forearm
		right_wrist
		right_hand
		right_hand_camera
		right_hand_camera_axis
		right_hand_range
		right_gripper_base
		right_gripper

	-name: arm
	joints:
		left_torso_arm_mount
		left_s0
		left_s1
		left_e0
		left_e1
		left_w0
		left_w0_to_itb_fixed
		left_w1
		left_w2
		left_hand
		left_hand_camera
		left_hand_camera_axis
		left_hand_range
		left_gripper_base
		left_endpoint
		right_torso_arm_mount
		right_s0
		right_s1
		right_e0
		right_e1
		right_w0
		right_w0_to_itb_fixed
		right_w1
		right_w2
		right_hand
		right_hand_camera
		right_hand_camera_axis
		right_hand_range
		right_gripper_base
		right_endpoint

	links:
		left_arm_mount
		left_upper_shoulder
		left_lower_shoulder
		left_upper_elbow
		left_lower_elbow
		left_upper_forearm
		left_arm_itb
		left_lower_forearm
		left_wrist
		left_hand
		left_hand_camera
		left_hand_camera_axis
		left_hand_range
		left_gripper_base
		left_gripper
		right_arm_mount
		right_upper_shoulder
		right_lower_shoulder
		right_upper_elbow
		right_lower_elbow
		right_upper_forearm
		right_arm_itb
		right_lower_forearm
		right_wrist
		right_hand
		right_hand_camera
		right_hand_camera_axis
		right_hand_range
		right_gripper_base
		right_gripper


